version: '3'

networks:
  simple_network:
    driver: bridge

services:
  db:
    image: mysql:8.0.29
    container_name: mysql_container
    restart: always
    networks:
      - simple_network
    env_file:
      - .env
    # environment:
    #   - MYSQL_DATABASE=test_db
    #   - MYSQL_ROOT_PASSWORD=3gjF66W3cRI
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin_container
    networks:
      - simple_network
    depends_on:
      - db
    # environment:
    #   PMA_HOST: db
    #   MYSQL_ROOT_PASSWORD: 3gjF66W3cRI
    #   PMA_ABSOLUTE_URI: http://jenkins.gapmoe.net/pma/
    restart: always
  node_app:
    image: node_app_image
    build: ./src
    restart: always
    networks:
      - simple_network
    container_name: node_app_container
    depends_on:
      - db
  nginx:
    build: ./nginx
    image: nginx_image
    restart: always
    container_name: api_nginx
    networks:
      - simple_network
    ports:
      - 80:80
    volumes:
      - /apiDoc:/usr/share/nginx/html
    depends_on:
      - node_app
      - jenkins
      - phpmyadmin
  jenkins:
    restart: always
    image: jenkins-docker
    build: ./jenkins
    privileged: true
    networks:
      - simple_network
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_container
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /apiDoc:/apiDoc
      - /var/run/docker.sock:/var/run/docker.sock